import type { Metadata } from "next";
// Metadata 페이지의 헤더 내용에 포함시킬 메타데이터
import { Inter } from "next/font/google";
// 폰트 가져온 것. font/google : Inter
import "./globals.css";
// css 스타일 가져온 것.

// 폰트 적용
// Inter 폰트 생성 하면서 문자 집합 정해준 것, 어떤 문자 집합을 사용할건지 [] 적어줘야 함, Inter({subsets: [] });
const inter = Inter({ subsets: ["latin"] });

// 이 양식도 정해져 있어서 그대로 써야 함 = export const metadata: Metadata
// 메타데이터 지정
export const metadata: Metadata = {
  title: "Create Next App", // 페이지의 제목
  description: "Generated by create next app", // 페이지의 설명
};

// 처음에 전역으로 사용할 레이아웃
// 이 레이아웃은 제거하면 안된다.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // React node 타입이다.
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        여기는 루트 레이아웃
        {children}
      </body>
    </html>
  );
}

// props : children, 바디 객체 안에 children으로 본문 내용 받고, 폰트 클래스 적용
